apiVersion: v1
kind: Service
metadata:
  name: ftps
  namespace: default
  labels:
    app: ftps-app
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  ports:
    - name: data
      port: 20
      targetPort: 20
    - name: ftps
      port: 21
      protocol: TCP
      targetPort: 21
    - name: ftps-pasv
      port: 30020
      protocol: TCP
      targetPort: 30020
    - name: ftps-pasv2
      port: 30021
      protocol: TCP
      targetPort: 30021
  selector:
    app: ftps-app
  type: LoadBalancer
  loadBalancerIP: 192.168.99.240

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  namespace: default
  labels:
    app: ftps-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps-app
  template:
    metadata:
      labels:
        app: ftps-app
    spec:
      containers:
      - name: sftp
        image: ft_ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 20
        - containerPort: 21
        - containerPort: 30020
        - containerPort: 30021
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /etc/ftps/ftp_admin
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
      restartPolicy: Always
