apiVersion: v1
kind: Service
metadata:
  name: grafana
  labels:
    app: grafana-app
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: grafana-app
  type: LoadBalancer
  loadBalancerIP: 192.168.99.240
  externalTrafficPolicy: Cluster

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: default
  labels:
    app: grafana-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-app
  template:
    metadata:
      labels:
        app: grafana-app
    spec:
      containers:
      - name: grafana
        image: ft_grafana
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
          name: grafana
      restartPolicy: Always