apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin-app
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: phpmyadmin-app
  type: LoadBalancer
  loadBalancerIP: 192.168.99.240
  externalTrafficPolicy: Cluster

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  namespace: default
  labels:
    app: phpmyadmin-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin-app
  template:
    metadata:
      labels:
        app: phpmyadmin-app
    spec:
      containers:
      - name: phpmyadmin
        image: ft_phpmyadmin
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
          name: phpmyadmin
      restartPolicy: Always