apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress-app
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  ports:
    - port: 5050
      targetPort: 5050
  selector:
    app: wordpress-app
  type: LoadBalancer
  loadBalancerIP: 192.168.99.240
  externalTrafficPolicy: Cluster

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: default
  labels:
    app: wordpress-app
spec:
  selector:
    matchLabels:
      app: wordpress-app
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress-app
    spec:
      containers:
      - image: ft_wordpress
        name: wordpress
        imagePullPolicy: Never
        env:
        ports:
        - containerPort: 5050
          name: wordpress
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /var/www/localhost
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wp-pv-claim
      restartPolicy: Always